on: 
  push:
  pull_request:

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v2.3.5

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: test

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: -- -D warnings
